name: tolstoy_flutter_sdk
description: "Tolstoy Flutter SDK"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  http: ^0.13.5
  visibility_detector: ^0.4.0+2
  uuid: ^3.0.1
  path: ^1.5.0
  collection: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TolstoyLogo.png
