name: tolstoy_flutter_sdk
description: "Tolstoy Flutter SDK"
publish_to: 'none'
version: 0.1.19

environment:
  sdk: ^3.3.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  path: ^1.9.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  uuid: ^4.4.0
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TolstoyLogo.png
