name: tolstoy_flutter_sdk
description: "Tolstoy Flutter SDK"
publish_to: 'none'
version: 0.1.8

environment:
  sdk: ^3.3.0

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.14.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.5.0
  uuid: ^3.0.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TolstoyLogo.png
