name: tolstoy_flutter_sdk
description: "Tolstoy Flutter SDK"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

executables:
  update_tolstoy_sdk:
    main: ./scripts/update.dart
